name: Teleport-To-Friend-PAF-Extension
api-version: 1.13
version: ${project.version}
author: Simonsator
depend: [PartyAndFriendsGUI]
depends: [PartyAndFriendsGUI]
main: de.simonsator.partyandfriends.extentions.teleporttofriends.bukkit.TTFBukkitPlugin
description: An add-on for party and friends extended to teleport players to their friend when they jump to them